development:
    adapter: postgresql
    encoding: unicode
    database: angel-test-app
    host: localhost
    username: postgres
    password: postgres
staging:
    adapter: postgresql
    encoding: unicode
    database: angel-test-app
    host: localhost
    username: postgres
    password: postgres
production:
    adapter: postgresql
    encoding: unicode
    database: angel-test-app
    host: localhost
    username: postgres
    password: postgres
