development:
    adapter: postgresql
    encoding: unicode
    database: angel-test-app
    host: localhost
    username: postgres
    password: postgres
test:
    adapter: postgresql
    encoding: unicode
    database: angel-test-app-test
    host: localhost
    username: postgres
    password: postgres